### ISSUE TITLE
Wasm version has additional space when running in Firefox

### ISSUE THREAD

**Issue by sedyh** [drpaneas/pong#1]
Looks like there is some extra space when running the game in Firefox:
![image](https://user-images.githubusercontent.com/19890545/221202245-7d2c4837-8d17-4833-b007-4d1182573da9.png)

**Comment by sedyh** [comment]
Looks like there are two canvases.
![image](https://user-images.githubusercontent.com/19890545/221203196-21acbd78-a6ec-47fa-b526-4e32887127de.png)

**Comment by drpaneas** [comment]
Thanks for filling the bug. It should be working now ;)

![Screenshot 2023-02-27 at 02 15 28](https://user-images.githubusercontent.com/2141732/221450415-4d923707-51b2-48e6-b4ac-1444dfd78525.png)
